name: Rust

on:
  schedule:
    - cron:  '0 0 * * *'

env:
  CARGO_TERM_COLOR: always
  DO_ICON_GENERATION: 'true'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cargo build --verbose
        cargo fmt
        git add -A
        git commit
        git push
