name: Rust

on:
  schedule:
    - cron:  '0 0 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build
      uses: actions/checkout@v2
      run: |
        cargo build --verbose
        cargo fmt
        git add -A
        git commit
        git push
